### PR TITLE
add ability to detect container engine

### PR DESCRIPTION
**Pull request by ofrobots**
Needed for https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2125.

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Just some quick notes

- can you make sure everything is kept in alphabetical order? vars/fns
- please use `function (` as opposed to `function(` in all places

**Comment by stephenplusplus** [comment]
- no `res` needed in the new function

- missing semicolon

(can't comment by line, getting a GH error)

**Comment by ofrobots** [comment]
Addressed comments. PTAL.

**Comment by stephenplusplus** [comment]
Published under 0.6.0

**Pull request merged**
