### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ace-n**
As title. Required to fix authentication on Container Builder, and integrate the [new release](https://github.com/google/google-auth-library-nodejs/releases/tag/v1.2.0) of `google-auth-library`.

**Note:** ideally, this would be a patch or minor version bump. If this change involves a _major_ version bump, we'll have to update any dependents in order to fix the Container Builder issues.

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Thanks! Published as 0.9.2

**Comment by ofrobots** [comment]
It is great that this landed, but there is no CI in this repo, and the changes over in google-auth-library have been quite substantial. It would to add a CI, or possibly move the functionality from here to google-auth-library itself. /cc @JustinBeckwith

**Comment by stephenplusplus** [comment]
I ran locally before publishing. I have an issue to open CI here: https://github.com/stephenplusplus/google-auto-auth/issues/32

But, generally agree: if google-auth-library can make auth easier, like this library, then we should blow this one up.

(A discussion on this should probably happen in a different issue, depending on the direction you want to take: ["let's move functionality"](https://github.com/google/google-auth-library-nodejs/issues/54) vs ["we need CI"](https://github.com/stephenplusplus/google-auto-auth/issues/32))

**Comment by ofrobots** [comment]
I think a CI should exist regardless. There is already an issue open for it: https://github.com/stephenplusplus/google-auto-auth/issues/32

**Comment by stephenplusplus** [comment]
@ace-n @ofrobots I had to revert. Would anyone be willing to send another PR, given the changes noted in #35? As I recall, I initially tested against the 1.0.0 pre-release, and things worked fine without changes. It would probably be quicker for someone more familiar with 1.2.0 to take a shot at this.

**Comment by ace-n** [comment]
That might be something for @ofrobots to look into - as I'm not very familiar with these libraries, and simply massaged them until `npm test` passed. (Another reason why we should have CI + solid testing, as @ofrobots mentioned above.)

**Comment by stephenplusplus** [comment]
We all want CI, we just need to get around to adding it :)

RE: solid testing, we could definitely use some real integration tests.

**Pull request merged**
