### PR TITLE
test: fix re-use existing authClient test

### PR DESCRIPTION
**Pull request by ofrobots**
I believe this got broken by https://github.com/stephenplusplus/google-auto-auth/pull/21.

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Can you explain more how this was broken? It also doesn't seem like the test that's been changed is still testing what it says it is (re-using a cached auth client).

**Comment by ofrobots** [comment]
With #21, if an `authClient` exists, we simply return it. The test was mocking `authClient` but and expecting `authClientPromise` would resolve to the mocked value of `authClient`.

**Comment by stephenplusplus** [comment]
Is this line tested anywhere? https://github.com/stephenplusplus/google-auto-auth/blob/ac4daa66d68d0280cc6b7345fee2583ad838de37/index.js#L111

**Comment by ofrobots** [comment]
Not only was that line untested, it was unreachable. PTAL.

**Comment by ofrobots** [comment]
Actually it still might benefit from an additional test. Adding.

**Pull request merged**
